server:
  port: 8888

spring:
  application:
    name: config-serveice
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KimTaeKang57/spring-msa-config
#          uri: file:///Users/kimtaekang/Desktop/study/git-local-repo