server:
  port: 8000
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultzone: http//localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
#          uri: lb://USER-SERVICE
          uri: http://localhost:9001/
          predicates:
            - Path=/user-service/**

